In [ ]:
import io
import pandas as pd
import pyspark
from pyspark import *
from pyspark.sql import *

# Initialize SparkContext
# sc = SparkContext.getOrCreate()
spark = SparkSession.builder.appName("DateTimeFunctions").getOrCreate()
from pyspark.sql.functions import *
# create sample DataFrame

data = [("2022-03-15", "2022-03-16 12:34:56.789"),

("2022-03-01", "2022-03-16 01:23:45.678")]

df = spark.createDataFrame(data, ["date_col","timestamp_col"])

df.select(current_date()).show()
df.select(current_timestamp()).show(truncate=False)
df.select(date_add("date_col", 5), date_sub("date_col",10)).show()
df.select(datediff("timestamp_col","date_col").alias("date_diff")).show()
df.select(year("date_col"), dayofyear("date_col"),month("date_col"), dayofmonth("date_col")).show()

df.select(hour("timestamp_col"), minute("timestamp_col"),
second("timestamp_col")).show()



# df.select(unix_timestamp("timestamp_col")).show()

# df.select(to_timestamp("date_col","yyyy-MM-dd").alias("date"),to_timestamp("timestamp_col", "yyyy-MM-dd HH:mm:ss.SSS").alias("timestamp")).show(truncate=False)

df.select(to_date("date_col",
"yyyy-MM-dd").alias("date")).show()

df.select(trunc("timestamp_col", "hour").alias("hour"),
trunc("timestamp_col", "minute").alias("minute"),
trunc("timestamp_col", "day").alias("day")).show()

df.select(months_between("timestamp_col",
"date_col").alias("months_between")).show()

+--------------+
|current_date()|
+--------------+
|    2025-08-01|
|    2025-08-01|
+--------------+

+--------------------------+
|current_timestamp()       |
+--------------------------+
|2025-08-01 11:56:33.334581|
|2025-08-01 11:56:33.334581|
+--------------------------+

+---------------------+----------------------+
|date_add(date_col, 5)|date_sub(date_col, 10)|
+---------------------+----------------------+
|           2022-03-20|            2022-03-05|
|           2022-03-06|            2022-02-19|
+---------------------+----------------------+

+---------+
|date_diff|
+---------+
|        1|
|       15|
+---------+

+--------------+-------------------+---------------+--------------------+
|year(date_col)|dayofyear(date_col)|month(date_col)|dayofmonth(date_col)|
+--------------+-------------------+---------------+--------------------+
|          2022|                 74|              3|                  15|
|          2022|                 60|              3|                   1|
+--------------+-------------------+---------------+--------------------+

+-------------------+---------------------+---------------------+
|hour(timestamp_col)|minute(timestamp_col)|second(timestamp_col)|
+-------------------+---------------------+---------------------+
|                 12|                   34|                   56|
|                  1|                   23|                   45|
+-------------------+---------------------+---------------------+

+----------+
|      date|
+----------+
|2022-03-15|
|2022-03-01|
+----------+

+----+------+----+
|hour|minute| day|
+----+------+----+
|NULL|  NULL|NULL|
|NULL|  NULL|NULL|
+----+------+----+

+--------------+
|months_between|
+--------------+
|    0.04916965|
|    0.48574709|
+--------------+